//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_product
    {
        public int id { get; set; }
        public int id_pr { get; set; }
        public int id_ord { get; set; }
        public int Col { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Producti Producti { get; set; }
    }
}
