//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producti()
        {
            this.Order_product = new HashSet<Order_product>();
        }
    
        public int id { get; set; }
        public int id_prod_categoty { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Kol { get; set; }
        public string Shtrihcode { get; set; }
        public byte[] Images { get; set; }
    
        public virtual Categ_tovar Categ_tovar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_product> Order_product { get; set; }
    }
}
